apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-deploymnet
spec:
 selector:
  matchLabels:
    app: myapp
replicas: 2
template:
  metadata:
    lables:
      app: myapp
  spec:
    containers:
    - name: myapp
      image: nanajanshia/argocd-app:1.0
      ports:
      - containerPort: 8080
